
// We are modularizing this manually because the current modularize setting in Emscripten has some issues:
// https://github.com/kripken/emscripten/issues/5820
// In addition, When you use emcc's modularization, it still expects to export a global object called `Module`,
// which is able to be used/called before the WASM is loaded.
// The modularization below exports a promise that loads and resolves to the actual sql.js module.
// That way, this module can't be used before the WASM is finished loading.

// We are going to define a function that a user will call to start loading initializing our Sql.js library
// However, that function might be called multiple times, and on subsequent calls, we don't actually want it to instantiate a new instance of the Module
// Instead, we want to return the previously loaded module

// TODO: Make this not declare a global if used in the browser

var initSqlJsPromise = undefined;

var SQL = (function (moduleConfig) {

    if (initSqlJsPromise){
      return initSqlJsPromise;
    }
    // If we're here, we've never called this function before
   // initSqlJsPromise = new Promise((resolveModule, reject) => {

        // We are modularizing this manually because the current modularize setting in Emscripten has some issues:
        // https://github.com/kripken/emscripten/issues/5820

        // The way to affect the loading of emcc compiled modules is to create a variable called `Module` and add
        // properties to it, like `preRun`, `postRun`, etc
        // We are using that to get notified when the WASM has finished loading.
        // Only then will we return our promise

        // If they passed in a moduleConfig object, use that
        // Otherwise, initialize Module to the empty object
        var Module = typeof moduleConfig !== 'undefined' ? moduleConfig : {};

        // EMCC only allows for a single onAbort function (not an array of functions)
        // So if the user defined their own onAbort function, we remember it and call it
        var originalOnAbortFunction = Module['onAbort'];
        Module['onAbort'] = function (errorThatCausedAbort) {
            reject(new Error(errorThatCausedAbort));
            if (originalOnAbortFunction){
              originalOnAbortFunction(errorThatCausedAbort);
            }
        };

        Module['postRun'] = Module['postRun'] || [];
        Module['postRun'].push(function () {
            // When Emscripted calls postRun, this promise resolves with the built Module
            //resolveModule(Module);
			Promise.resolve(Module);
        });

        // There is a section of code in the emcc-generated code below that looks like this:
        // (Note that this is lowercase `module`)
        // if (typeof module !== 'undefined') {
        //     module['exports'] = Module;
        // }
        // When that runs, it's going to overwrite our own modularization export efforts in shell-post.js!
        // The only way to tell emcc not to emit it is to pass the MODULARIZE=1 or MODULARIZE_INSTANCE=1 flags,
        // but that carries with it additional unnecessary baggage/bugs we don't want either.
        // So, we have three options:
        // 1) We undefine `module`
        // 2) We remember what `module['exports']` was at the beginning of this function and we restore it later
        // 3) We write a script to remove those lines of code as part of the Make process.
        //
        // Since those are the only lines of code that care about module, we will undefine it. It's the most straightforward
        // of the options, and has the side effect of reducing emcc's efforts to modify the module if its output were to change in the future.
        // That's a nice side effect since we're handling the modularization efforts ourselves
        module = undefined;
        
        // The emcc-generated code and shell-post.js code goes below,
        // meaning that all of it runs inside of this promise. If anything throws an exception, our promise will abort
var f,h;var l;l||(l=typeof Module !== 'undefined' ? Module : {});
var ua=function(){var a;var b=n(4);var c={};var d=function(){function a(a,b){this.eb=a;this.db=b;this.lb=1;this.Bb=[]}a.prototype.bind=function(a){if(!this.eb)throw"Statement closed";this.reset();return Array.isArray(a)?this.Xb(a):this.Yb(a)};a.prototype.step=function(){var a;if(!this.eb)throw"Statement closed";this.lb=1;switch(a=Xb(this.eb)){case c.Tb:return!0;case c.DONE:return!1;default:return this.db.handleError(a)}};a.prototype.dc=function(a){null==a&&(a=this.lb++);return Yb(this.eb,a)};a.prototype.ec=
function(a){null==a&&(a=this.lb++);return Zb(this.eb,a)};a.prototype.getBlob=function(a){var b;null==a&&(a=this.lb++);var c=$b(this.eb,a);var d=ac(this.eb,a);var e=new Uint8Array(c);for(a=b=0;0<=c?b<c:b>c;a=0<=c?++b:--b)e[a]=p[d+a];return e};a.prototype.get=function(a){var b,d;null!=a&&this.bind(a)&&this.step();var e=[];a=b=0;for(d=mb(this.eb);0<=d?b<d:b>d;a=0<=d?++b:--b)switch(bc(this.eb,a)){case c.Sb:case c.FLOAT:e.push(this.dc(a));break;case c.Ub:e.push(this.ec(a));break;case c.Rb:e.push(this.getBlob(a));
break;default:e.push(null)}return e};a.prototype.getColumnNames=function(){var a,b;var c=[];var d=a=0;for(b=mb(this.eb);0<=b?a<b:a>b;d=0<=b?++a:--a)c.push(cc(this.eb,d));return c};a.prototype.getAsObject=function(a){var b,c;var d=this.get(a);var e=this.getColumnNames();var g={};a=b=0;for(c=e.length;b<c;a=++b){var Wb=e[a];g[Wb]=d[a]}return g};a.prototype.run=function(a){null!=a&&this.bind(a);this.step();return this.reset()};a.prototype.ac=function(a,b){var c;null==b&&(b=this.lb++);a=aa(a);this.Bb.push(c=
ba(a));this.db.handleError(da(this.eb,b,c,a.length-1,0))};a.prototype.Wb=function(a,b){var c;null==b&&(b=this.lb++);this.Bb.push(c=ba(a));this.db.handleError(Ma(this.eb,b,c,a.length,0))};a.prototype.$b=function(a,b){null==b&&(b=this.lb++);this.db.handleError((a===(a|0)?dc:ec)(this.eb,b,a))};a.prototype.Zb=function(a){null==a&&(a=this.lb++);Ma(this.eb,a,0,0,0)};a.prototype.Ib=function(a,b){null==b&&(b=this.lb++);switch(typeof a){case "string":this.ac(a,b);break;case "number":case "boolean":this.$b(a+
0,b);break;case "object":if(null===a)this.Zb(b);else if(null!=a.length)this.Wb(a,b);else throw"Wrong API use : tried to bind a value of an unknown type ("+a+").";}};a.prototype.Yb=function(a){var b;for(b in a){var c=a[b];var d=fc(this.eb,b);0!==d&&this.Ib(c,d)}return!0};a.prototype.Xb=function(a){var b,c;var d=b=0;for(c=a.length;b<c;d=++b){var e=a[d];this.Ib(e,d+1)}return!0};a.prototype.reset=function(){this.freemem();return hc(this.eb)===c.vb&&ic(this.eb)===c.vb};a.prototype.freemem=function(){for(var a;a=
this.Bb.pop();)ca(a);return null};a.prototype.free=function(){this.freemem();var a=jc(this.eb)===c.vb;delete this.db.zb[this.eb];this.eb=ea;return a};return a}();var e=function(){function a(a){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=a){var c=this.filename,d=c?q("/",c):"/";c=fa(!0,!0);d=ia(d,(void 0!==c?c:438)&4095|32768,0);if(a){if("string"===typeof a){for(var e=Array(a.length),k=0,m=a.length;k<m;++k)e[k]=a.charCodeAt(k);a=e}ja(d,c|146);e=r(d,"w");ka(e,a,0,a.length,0,void 0);
la(e);ja(d,c)}}this.handleError(g(this.filename,b));this.db=t(b,"i32");kc(this.db);this.zb={}}a.prototype.run=function(a,c){if(!this.db)throw"Database closed";c?(a=this.prepare(a,c),a.step(),a.free()):this.handleError(m(this.db,a,0,0,b));return this};a.prototype.exec=function(a){if(!this.db)throw"Database closed";var c=ma();var e=na(a)+1;var g=n(e);u(a,p,g,e);a=g;e=n(4);for(g=[];t(a,"i8")!==ea;){oa(b);oa(e);this.handleError(ha(this.db,a,-1,b,e));var k=t(b,"i32");a=t(e,"i32");if(k!==ea){var m=new d(k,
this);for(k=null;m.step();)null===k&&(k={columns:m.getColumnNames(),values:[]},g.push(k)),k.values.push(m.get());m.free()}}pa(c);return g};a.prototype.each=function(a,b,c,d){"function"===typeof b&&(d=c,c=b,b=void 0);for(a=this.prepare(a,b);a.step();)c(a.getAsObject());a.free();if("function"===typeof d)return d()};a.prototype.prepare=function(a,c){oa(b);this.handleError(z(this.db,a,-1,b,ea));a=t(b,"i32");if(a===ea)throw"Nothing to prepare";var e=new d(a,this);null!=c&&e.bind(c);return this.zb[a]=e};
a.prototype["export"]=function(){var a;var c=this.zb;for(e in c){var d=c[e];d.free()}this.handleError(k(this.db));d=this.filename;var e=e={encoding:"binary"};e.flags=e.flags||"r";e.encoding=e.encoding||"binary";if("utf8"!==e.encoding&&"binary"!==e.encoding)throw Error('Invalid encoding type "'+e.encoding+'"');c=r(d,e.flags);d=qa(d).size;var m=new Uint8Array(d);ra(c,m,0,d,0);"utf8"===e.encoding?a=v(m,0):"binary"===e.encoding&&(a=m);la(c);this.handleError(g(this.filename,b));this.db=t(b,"i32");return a};
a.prototype.close=function(){var a;var b=this.zb;for(a in b){var c=b[a];c.free()}this.handleError(k(this.db));sa("/"+this.filename);return this.db=null};a.prototype.handleError=function(a){if(a===c.vb)return null;a=lc(this.db);throw Error(a);};a.prototype.getRowsModified=function(){return y(this.db)};a.prototype.create_function=function(a,b){var d=ta(function(a,c,d){var e,g;var k=[];for(e=g=0;0<=c?g<c:g>c;e=0<=c?++g:--g){var m=t(d+4*e,"i32");var z=nc(m);e=function(){switch(!1){case 1!==z:return oc;
case 2!==z:return pc;case 3!==z:return qc;case 4!==z:return function(a){var b,c;var d=rc(a);var e=sc(a);a=new Uint8Array(d);for(b=c=0;0<=d?c<d:c>d;b=0<=d?++c:--c)a[b]=p[e+b];return a};default:return function(){return null}}}();e=e(m);k.push(e)}if(c=b.apply(null,k))switch(typeof c){case "number":return tc(a,c);case "string":return uc(a,c,-1,-1)}else return vc(a)});this.handleError(wc(this.db,a,b.length,c.Vb,0,d,0,0,0));return this};return a}();var g=l.cwrap("sqlite3_open","number",["string","number"]);
var k=l.cwrap("sqlite3_close_v2","number",["number"]);var m=l.cwrap("sqlite3_exec","number",["number","string","number","number","number"]);l.cwrap("sqlite3_free","",["number"]);var y=l.cwrap("sqlite3_changes","number",["number"]);var z=l.cwrap("sqlite3_prepare_v2","number",["number","string","number","number","number"]);var ha=l.cwrap("sqlite3_prepare_v2","number",["number","number","number","number","number"]);var da=l.cwrap("sqlite3_bind_text","number",["number","number","number","number","number"]);
var Ma=l.cwrap("sqlite3_bind_blob","number",["number","number","number","number","number"]);var ec=l.cwrap("sqlite3_bind_double","number",["number","number","number"]);var dc=l.cwrap("sqlite3_bind_int","number",["number","number","number"]);var fc=l.cwrap("sqlite3_bind_parameter_index","number",["number","string"]);var Xb=l.cwrap("sqlite3_step","number",["number"]);var lc=l.cwrap("sqlite3_errmsg","string",["number"]);var mb=l.cwrap("sqlite3_data_count","number",["number"]);var Yb=l.cwrap("sqlite3_column_double",
"number",["number","number"]);var Zb=l.cwrap("sqlite3_column_text","string",["number","number"]);var ac=l.cwrap("sqlite3_column_blob","number",["number","number"]);var $b=l.cwrap("sqlite3_column_bytes","number",["number","number"]);var bc=l.cwrap("sqlite3_column_type","number",["number","number"]);var cc=l.cwrap("sqlite3_column_name","string",["number","number"]);var ic=l.cwrap("sqlite3_reset","number",["number"]);var hc=l.cwrap("sqlite3_clear_bindings","number",["number"]);var jc=l.cwrap("sqlite3_finalize",
"number",["number"]);var wc=l.cwrap("sqlite3_create_function_v2","number","number string number number number number number number number".split(" "));var nc=l.cwrap("sqlite3_value_type","number",["number"]);var rc=l.cwrap("sqlite3_value_bytes","number",["number"]);var qc=l.cwrap("sqlite3_value_text","string",["number"]);var oc=l.cwrap("sqlite3_value_int","number",["number"]);var sc=l.cwrap("sqlite3_value_blob","number",["number"]);var pc=l.cwrap("sqlite3_value_double","number",["number"]);var tc=
l.cwrap("sqlite3_result_double","",["number","number"]);var vc=l.cwrap("sqlite3_result_null","",["number"]);var uc=l.cwrap("sqlite3_result_text","",["number","string","number","number"]);var kc=l.cwrap("RegisterExtensionFunctions","number",["number"]);this.SQL={Database:e};for(a in this.SQL)l[a]=this.SQL[a];var ea=0;c.vb=0;c.uc=1;c.xc=2;c.Hc=3;c.oc=4;c.qc=5;c.Ac=6;c.NOMEM=7;c.Kc=8;c.yc=9;c.zc=10;c.tc=11;c.NOTFOUND=12;c.wc=13;c.rc=14;c.Ic=15;c.EMPTY=16;c.Lc=17;c.Mc=18;c.sc=19;c.Bc=20;c.Cc=21;c.Dc=
22;c.pc=23;c.vc=24;c.Jc=25;c.Ec=26;c.Fc=27;c.Nc=28;c.Tb=100;c.DONE=101;c.Sb=1;c.FLOAT=2;c.Ub=3;c.Rb=4;c.Gc=5;c.Vb=1}.bind(this);l.preRun=l.preRun||[];l.preRun.push(ua);var va={},w;for(w in l)l.hasOwnProperty(w)&&(va[w]=l[w]);l.arguments=[];l.thisProgram="./this.program";l.quit=function(a,b){throw b;};l.preRun=[];l.postRun=[];var wa=!1,x=!1,A=!1,xa=!1;wa="object"===typeof window;x="function"===typeof importScripts;A="object"===typeof process&&"function"===typeof require&&!wa&&!x;xa=!wa&&!A&&!x;
var B="";
if(A){B=__dirname+"/";var ya,za;l.read=function(a,b){ya||(ya=require("fs"));za||(za=require("path"));a=za.normalize(a);a=ya.readFileSync(a);return b?a:a.toString()};l.readBinary=function(a){a=l.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(l.thisProgram=process.argv[1].replace(/\\/g,"/"));l.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=l);process.on("unhandledRejection",C);l.quit=function(a){process.exit(a)};l.inspect=function(){return"[Emscripten Module object]"}}else if(xa)"undefined"!=
typeof read&&(l.read=function(a){return read(a)}),l.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?l.arguments=scriptArgs:"undefined"!=typeof arguments&&(l.arguments=arguments),"function"===typeof quit&&(l.quit=function(a){quit(a)});else if(wa||x)x?B=self.location.href:document.currentScript&&(B=document.currentScript.src),B=0!==B.indexOf("blob:")?B.substr(0,B.lastIndexOf("/")+
1):"",l.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},x&&(l.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),l.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},l.setWindowTitle=function(a){document.title=
a};var Aa=l.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),D=l.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||Aa);for(w in va)va.hasOwnProperty(w)&&(l[w]=va[w]);va=void 0;function Ba(a){var b=E[Ca>>2];a=b+a+15&-16;if(a<=Da())E[Ca>>2]=a;else if(!Ea(a))return 0;return b}var Fa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},Ga=1,F=Array(64);
function ta(a){for(var b=0;64>b;b++)if(!F[b])return F[b]=a,Ga+b;throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";}"object"!==typeof WebAssembly&&D("no native wasm support detected");
function t(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return p[a>>0];case "i8":return p[a>>0];case "i16":return Ha[a>>1];case "i32":return E[a>>2];case "i64":return E[a>>2];case "float":return Ia[a>>2];case "double":return Ja[a>>3];default:C("invalid type for getValue: "+b)}return null}var Ka,La=!1;function assert(a,b){a||C("Assertion failed: "+b)}function Na(a){var b=l["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Oa(a,b,c,d){var e={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=n(c);u(a,G,b,c)}return b},array:function(a){var b=n(a.length);p.set(a,b);return b}},g=Na(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var y=e[c[m]];y?(0===a&&(a=ma()),k[m]=y(d[m])):k[m]=d[m]}c=g.apply(null,k);c=function(a){return"string"===b?H(a):"boolean"===b?!!a:a}(c);0!==a&&pa(a);return c}
function oa(a){var b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":p[a>>0]=0;break;case "i8":p[a>>0]=0;break;case "i16":Ha[a>>1]=0;break;case "i32":E[a>>2]=0;break;case "i64":f=[0,(h=0,1<=+Pa(h)?0<h?(Qa(+Ra(h/4294967296),4294967295)|0)>>>0:~~+Sa((h-+(~~h>>>0))/4294967296)>>>0:0)];E[a>>2]=f[0];E[a+4>>2]=f[1];break;case "float":Ia[a>>2]=0;break;case "double":Ja[a>>3]=0;break;default:C("invalid type for setValue: "+b)}}var Ta=0,Ua=3;
function ba(a){var b=Ta;if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=b==Ua?e:[Va,n,Ba][b](Math.max(d,1));if(c){var e=b;assert(0==(b&3));for(a=b+(d&-4);e<a;e+=4)E[e>>2]=0;for(a=b+d;e<a;)p[e++>>0]=0;return b}a.subarray||a.slice?G.set(a,b):G.set(new Uint8Array(a),b);return b}var Wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function v(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Wa)return Wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function H(a){return a?v(G,a,void 0):""}
function u(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Xa(a){return a.replace(/__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}function Ya(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,p,G,Ha,E,Ia,Ja;
function Za(){l.HEAP8=p=new Int8Array(buffer);l.HEAP16=Ha=new Int16Array(buffer);l.HEAP32=E=new Int32Array(buffer);l.HEAPU8=G=new Uint8Array(buffer);l.HEAPU16=new Uint16Array(buffer);l.HEAPU32=new Uint32Array(buffer);l.HEAPF32=Ia=new Float32Array(buffer);l.HEAPF64=Ja=new Float64Array(buffer)}var Ca=60896,$a=l.TOTAL_MEMORY||16777216;5242880>$a&&D("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+$a+"! (TOTAL_STACK=5242880)");
l.buffer?buffer=l.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(Ka=new WebAssembly.Memory({initial:$a/65536}),buffer=Ka.buffer):buffer=new ArrayBuffer($a);Za();E[Ca>>2]=5303808;function ab(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.cc;"number"===typeof c?void 0===b.Cb?l.dynCall_v(c):l.dynCall_vi(c,b.Cb):c(void 0===b.Cb?null:b.Cb)}}}var bb=[],cb=[],db=[],eb=[],fb=!1;function gb(){var a=l.preRun.shift();bb.unshift(a)}
var Pa=Math.abs,Sa=Math.ceil,Ra=Math.floor,Qa=Math.min,I=0,hb=null,ib=null;l.preloadedImages={};l.preloadedAudios={};function jb(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="sql-wasm.wasm";if(!jb()){var kb=J;J=l.locateFile?l.locateFile(kb,B):B+kb}
function lb(){try{if(l.wasmBinary)return new Uint8Array(l.wasmBinary);if(l.readBinary)return l.readBinary(J);throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}function nb(){return l.wasmBinary||!wa&&!x||"function"!==typeof fetch?new Promise(function(a){a(lb())}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return lb()})}
function ob(a){function b(a){l.asm=a.exports;I--;l.monitorRunDependencies&&l.monitorRunDependencies(I);0==I&&(null!==hb&&(clearInterval(hb),hb=null),ib&&(a=ib,ib=null,a()))}function c(a){b(a.instance)}function d(a){nb().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){D("failed to asynchronously prepare wasm: "+a);C(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:Fa};I++;l.monitorRunDependencies&&l.monitorRunDependencies(I);if(l.instantiateWasm)try{return l.instantiateWasm(e,
b)}catch(g){return D("Module.instantiateWasm callback failed with error: "+g),!1}l.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||jb()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(J,{credentials:"same-origin"}),e).then(c,function(a){D("wasm streaming compile failed: "+a);D("falling back to ArrayBuffer instantiation");d(c)});return{}}
l.asm=function(a,b){b.memory=Ka;b.table=new WebAssembly.Table({initial:2560,maximum:2560,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return ob(b)};cb.push({cc:function(){pb()}});var K={};
function qb(a){if(qb.pb){var b=E[a>>2];var c=E[b>>2]}else qb.pb=!0,K.USER=K.LOGNAME="web_user",K.PATH="/",K.PWD="/",K.HOME="/home/web_user",K.LANG="C.UTF-8",K._=l.thisProgram,c=fb?Va(1024):Ba(1024),b=fb?Va(256):Ba(256),E[b>>2]=c,E[a>>2]=b;a=[];var d=0,e;for(e in K)if("string"===typeof K[e]){var g=e+"="+K[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=g=a[e];for(var k=c,m=0;m<d.length;++m)p[k++>>0]=d.charCodeAt(m);p[k>>0]=0;E[b+
4*e>>2]=c;c+=g.length+1}E[b+4*a.length>>2]=0}function rb(a){l.___errno_location&&(E[l.___errno_location()>>2]=a);return a}function sb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function tb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=sb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ub(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function vb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function wb(){var a=Array.prototype.slice.call(arguments,0);return tb(a.join("/"))}function q(a,b){return tb(a+"/"+b)}
function xb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=sb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var yb=[];function zb(a,b){yb[a]={input:[],output:[],sb:b};Ab(a,Bb)}
var Bb={open:function(a){var b=yb[a.node.rdev];if(!b)throw new L(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.sb.flush(a.tty)},flush:function(a){a.tty.sb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.sb.Pb)throw new L(6);for(var e=0,g=0;g<d;g++){try{var k=a.tty.sb.Pb(a.tty)}catch(m){throw new L(5);}if(void 0===k&&0===e)throw new L(11);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.sb.Fb)throw new L(6);
try{for(var e=0;e<d;e++)a.tty.sb.Fb(a.tty,b[c+e])}catch(g){throw new L(5);}d&&(a.node.timestamp=Date.now());return e}},Cb={Pb:function(a){if(!a.input.length){var b=null;if(A){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{e=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(e,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=aa(b,!0)}return a.input.shift()},Fb:function(a,b){null===b||10===b?(Aa(v(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(Aa(v(a.output,0)),a.output=[])}},Db={Fb:function(a,b){null===b||10===b?(D(v(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&
(D(v(a.output,0)),a.output=[])}},M={kb:null,hb:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(1);M.kb||(M.kb={dir:{node:{jb:M.$a.jb,gb:M.$a.gb,lookup:M.$a.lookup,tb:M.$a.tb,rename:M.$a.rename,unlink:M.$a.unlink,rmdir:M.$a.rmdir,readdir:M.$a.readdir,symlink:M.$a.symlink},stream:{mb:M.cb.mb}},file:{node:{jb:M.$a.jb,gb:M.$a.gb},stream:{mb:M.cb.mb,read:M.cb.read,write:M.cb.write,Hb:M.cb.Hb,xb:M.cb.xb,yb:M.cb.yb}},link:{node:{jb:M.$a.jb,
gb:M.$a.gb,readlink:M.$a.readlink},stream:{}},Kb:{node:{jb:M.$a.jb,gb:M.$a.gb},stream:Eb}});c=Fb(a,b,c,d);N(c.mode)?(c.$a=M.kb.dir.node,c.cb=M.kb.dir.stream,c.ab={}):32768===(c.mode&61440)?(c.$a=M.kb.file.node,c.cb=M.kb.file.stream,c.fb=0,c.ab=null):40960===(c.mode&61440)?(c.$a=M.kb.link.node,c.cb=M.kb.link.stream):8192===(c.mode&61440)&&(c.$a=M.kb.Kb.node,c.cb=M.kb.Kb.stream);c.timestamp=Date.now();a&&(a.ab[b]=c);return c},Oc:function(a){if(a.ab&&a.ab.subarray){for(var b=[],c=0;c<a.fb;++c)b.push(a.ab[c]);
return b}return a.ab},Pc:function(a){return a.ab?a.ab.subarray?a.ab.subarray(0,a.fb):new Uint8Array(a.ab):new Uint8Array},Lb:function(a,b){var c=a.ab?a.ab.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.ab,a.ab=new Uint8Array(b),0<a.fb&&a.ab.set(c.subarray(0,a.fb),0))},kc:function(a,b){if(a.fb!=b)if(0==b)a.ab=null,a.fb=0;else{if(!a.ab||a.ab.subarray){var c=a.ab;a.ab=new Uint8Array(new ArrayBuffer(b));c&&a.ab.set(c.subarray(0,Math.min(b,a.fb)))}else if(a.ab||(a.ab=
[]),a.ab.length>b)a.ab.length=b;else for(;a.ab.length<b;)a.ab.push(0);a.fb=b}},$a:{jb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.fb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.nb=4096;b.blocks=Math.ceil(b.size/b.nb);return b},gb:function(a,b){void 0!==b.mode&&(a.mode=
b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.kc(a,b.size)},lookup:function(){throw Gb[2];},tb:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(g){}if(d)for(var e in d.ab)throw new L(39);}delete a.parent.ab[a.name];a.name=c;b.ab[c]=a;a.parent=b},unlink:function(a,b){delete a.ab[b]},rmdir:function(a,b){var c=O(a,b),d;for(d in c.ab)throw new L(39);delete a.ab[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ab)a.ab.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(22);return a.link}},cb:{read:function(a,b,c,d,e){var g=a.node.ab;if(e>=a.node.fb)return 0;a=Math.min(a.node.fb-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ab||a.ab.subarray)){if(g)return a.ab=b.subarray(c,
c+d),a.fb=d;if(0===a.fb&&0===e)return a.ab=new Uint8Array(b.subarray(c,c+d)),a.fb=d;if(e+d<=a.fb)return a.ab.set(b.subarray(c,c+d),e),d}M.Lb(a,e+d);if(a.ab.subarray&&b.subarray)a.ab.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ab[e+g]=b[c+g];a.fb=Math.max(a.fb,e+d);return d},mb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.fb);if(0>b)throw new L(22);return b},Hb:function(a,b,c){M.Lb(a.node,b+c);a.node.fb=Math.max(a.node.fb,b+c)},xb:function(a,b,c,d,e,g,k){if(32768!==
(a.node.mode&61440))throw new L(19);c=a.node.ab;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.fb)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=Va(d);if(!d)throw new L(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{jc:d,Ab:a}},yb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(19);if(e&2)return 0;M.cb.write(a,b,0,d,c,!1);return 0}}},P={wb:!1,mc:function(){P.wb=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);
P.Mb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Jb:function(a){return Buffer.pb?Buffer.from(a):new Buffer(a)},hb:function(a){assert(A);return P.createNode(null,"/",P.Ob(a.Eb.root),0)},createNode:function(a,b,c){if(!N(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(22);a=Fb(a,b,c);a.$a=P.$a;a.cb=P.cb;return a},Ob:function(a){try{var b=fs.lstatSync(a);P.wb&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new L(-c.bb);
}return b.mode},ib:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.hb.Eb.root);b.reverse();return wb.apply(null,b)},bc:function(a){a&=-2656257;var b=0,c;for(c in P.Mb)a&c&&(b|=P.Mb[c],a^=c);if(a)throw new L(22);return b},$a:{jb:function(a){a=P.ib(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(-c.bb);}P.wb&&!b.nb&&(b.nb=4096);P.wb&&!b.blocks&&(b.blocks=(b.size+b.nb-1)/b.nb|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,
size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,nb:b.nb,blocks:b.blocks}},gb:function(a,b){var c=P.ib(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(-d.bb);}},lookup:function(a,b){var c=q(P.ib(a),b);c=P.Ob(c);return P.createNode(a,b,c)},tb:function(a,b,c,d){a=P.createNode(a,b,c,d);b=P.ib(a);try{N(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new L(-e.bb);
}return a},rename:function(a,b,c){a=P.ib(a);b=q(P.ib(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(-d.bb);}},unlink:function(a,b){a=q(P.ib(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(-c.bb);}},rmdir:function(a,b){a=q(P.ib(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(-c.bb);}},readdir:function(a){a=P.ib(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(-b.bb);}},symlink:function(a,b,c){a=q(P.ib(a),b);try{fs.symlinkSync(c,
a)}catch(d){if(!d.code)throw d;throw new L(-d.bb);}},readlink:function(a){var b=P.ib(a);try{return b=fs.readlinkSync(b),b=Hb.relative(Hb.resolve(a.hb.Eb.root),b)}catch(c){if(!c.code)throw c;throw new L(-c.bb);}}},cb:{open:function(a){var b=P.ib(a.node);try{32768===(a.node.mode&61440)&&(a.ub=fs.openSync(b,P.bc(a.flags)))}catch(c){if(!c.code)throw c;throw new L(-c.bb);}},close:function(a){try{32768===(a.node.mode&61440)&&a.ub&&fs.closeSync(a.ub)}catch(b){if(!b.code)throw b;throw new L(-b.bb);}},read:function(a,
b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.ub,P.Jb(b.buffer),c,d,e)}catch(g){throw new L(-g.bb);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.ub,P.Jb(b.buffer),c,d,e)}catch(g){throw new L(-g.bb);}},mb:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.ub).size}catch(d){throw new L(-d.bb);}if(0>b)throw new L(22);return b}}},Ib=null,Jb={},Q=[],Kb=1,R=null,Lb=!0,S={},L=null,Gb={};
function T(a,b){a=xb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Nb:!0,Gb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Gb)throw new L(40);a=sb(a.split("/").filter(function(a){return!!a}),!1);var e=Ib;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=O(e,a[d]);c=q(c,a[d]);e.qb&&(!g||g&&b.Nb)&&(e=e.qb.root);if(!g||b.ob)for(g=0;40960===(e.mode&61440);)if(e=Mb(c),c=xb(ub(c),e),e=T(c,{Gb:b.Gb}).node,40<g++)throw new L(40);}return{path:c,node:e}}
function Nb(a){for(var b;;){if(a===a.parent)return a=a.hb.Qb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function Pb(a){var b=Ob(a.parent.id,a.name);a.rb=R[b];R[b]=a}function Qb(a){var b=Ob(a.parent.id,a.name);if(R[b]===a)R[b]=a.rb;else for(b=R[b];b;){if(b.rb===a){b.rb=a.rb;break}b=b.rb}}
function O(a,b){var c;if(c=(c=Rb(a,"x"))?c:a.$a.lookup?0:13)throw new L(c,a);for(c=R[Ob(a.id,b)];c;c=c.rb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$a.lookup(a,b)}
function Fb(a,b,c,d){Sb||(Sb=function(a,b,c,d){a||(a=this);this.parent=a;this.hb=a.hb;this.qb=null;this.id=Kb++;this.name=b;this.mode=c;this.$a={};this.cb={};this.rdev=d},Sb.prototype={},Object.defineProperties(Sb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Sb(a,b,c,d);Pb(a);return a}
function N(a){return 16384===(a&61440)}var Tb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ub(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Rb(a,b){if(Lb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function Vb(a,b){try{return O(a,b),17}catch(c){}return Rb(a,"wx")}
function mc(a,b,c){try{var d=O(a,b)}catch(e){return e.bb}if(a=Rb(a,"wx"))return a;if(c){if(!N(d.mode))return 20;if(d===d.parent||"/"===Nb(d))return 16}else if(N(d.mode))return 21;return 0}function xc(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new L(24);}
function yc(a,b){zc||(zc=function(){},zc.prototype={},Object.defineProperties(zc.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new zc,d;for(d in a)c[d]=a[d];a=c;b=xc(b);a.fd=b;return Q[b]=a}var Eb={open:function(a){a.cb=Jb[a.node.rdev].cb;a.cb.open&&a.cb.open(a)},mb:function(){throw new L(29);}};function Ab(a,b){Jb[a]={cb:b}}
function Ac(a,b){var c="/"===b,d=!b;if(c&&Ib)throw new L(16);if(!c&&!d){var e=T(b,{Nb:!1});b=e.path;e=e.node;if(e.qb)throw new L(16);if(!N(e.mode))throw new L(20);}b={type:a,Eb:{},Qb:b,ic:[]};a=a.hb(b);a.hb=b;b.root=a;c?Ib=a:e&&(e.qb=b,e.hb&&e.hb.ic.push(b))}function ia(a,b,c){var d=T(a,{parent:!0}).node;a=vb(a);if(!a||"."===a||".."===a)throw new L(22);var e=Vb(d,a);if(e)throw new L(e);if(!d.$a.tb)throw new L(1);return d.$a.tb(d,a,b,c)}function U(a,b){ia(a,(void 0!==b?b:511)&1023|16384,0)}
function Bc(a,b,c){"undefined"===typeof c&&(c=b,b=438);ia(a,b|8192,c)}function Cc(a,b){if(!xb(a))throw new L(2);var c=T(b,{parent:!0}).node;if(!c)throw new L(2);b=vb(b);var d=Vb(c,b);if(d)throw new L(d);if(!c.$a.symlink)throw new L(1);c.$a.symlink(c,b,a)}
function sa(a){var b=T(a,{parent:!0}).node,c=vb(a),d=O(b,c),e=mc(b,c,!1);if(e)throw new L(e);if(!b.$a.unlink)throw new L(1);if(d.qb)throw new L(16);try{S.willDeletePath&&S.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.$a.unlink(b,c);Qb(d);try{if(S.onDeletePath)S.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function Mb(a){a=T(a).node;if(!a)throw new L(2);if(!a.$a.readlink)throw new L(22);return xb(Nb(a.parent),a.$a.readlink(a))}function qa(a,b){a=T(a,{ob:!b}).node;if(!a)throw new L(2);if(!a.$a.jb)throw new L(1);return a.$a.jb(a)}function Dc(a){return qa(a,!0)}function ja(a,b){var c;"string"===typeof a?c=T(a,{ob:!0}).node:c=a;if(!c.$a.gb)throw new L(1);c.$a.gb(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Ec(a){var b;"string"===typeof a?b=T(a,{ob:!0}).node:b=a;if(!b.$a.gb)throw new L(1);b.$a.gb(b,{timestamp:Date.now()})}function Fc(a,b){if(0>b)throw new L(22);var c;"string"===typeof a?c=T(a,{ob:!0}).node:c=a;if(!c.$a.gb)throw new L(1);if(N(c.mode))throw new L(21);if(32768!==(c.mode&61440))throw new L(22);if(a=Rb(c,"w"))throw new L(a);c.$a.gb(c,{size:b,timestamp:Date.now()})}
function r(a,b,c,d){if(""===a)throw new L(2);if("string"===typeof b){var e=Tb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=tb(a);try{g=T(a,{ob:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new L(17);}else g=ia(a,c,0),e=!0;if(!g)throw new L(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!N(g.mode))throw new L(20);if(!e&&(c=g?40960===(g.mode&61440)?40:N(g.mode)&&
("r"!==Ub(b)||b&512)?21:Rb(g,Ub(b)):2))throw new L(c);b&512&&Fc(g,0);b&=-641;d=yc({node:g,path:Nb(g),flags:b,seekable:!0,position:0,cb:g.cb,nc:[],error:!1},d);d.cb.open&&d.cb.open(d);!l.logReadFiles||b&1||(Gc||(Gc={}),a in Gc||(Gc[a]=1,console.log("FS.trackingDelegate error on read file: "+a)));try{S.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),S.onOpenFile(a,g))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}
function la(a){if(null===a.fd)throw new L(9);a.Db&&(a.Db=null);try{a.cb.close&&a.cb.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null}function Hc(a,b,c){if(null===a.fd)throw new L(9);if(!a.seekable||!a.cb.mb)throw new L(29);if(0!=c&&1!=c&&2!=c)throw new L(22);a.position=a.cb.mb(a,b,c);a.nc=[]}
function ra(a,b,c,d,e){if(0>d||0>e)throw new L(22);if(null===a.fd)throw new L(9);if(1===(a.flags&2097155))throw new L(9);if(N(a.node.mode))throw new L(21);if(!a.cb.read)throw new L(22);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new L(29);b=a.cb.read(a,b,c,d,e);g||(a.position+=b);return b}
function ka(a,b,c,d,e,g){if(0>d||0>e)throw new L(22);if(null===a.fd)throw new L(9);if(0===(a.flags&2097155))throw new L(9);if(N(a.node.mode))throw new L(21);if(!a.cb.write)throw new L(22);a.flags&1024&&Hc(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new L(29);b=a.cb.write(a,b,c,d,e,g);k||(a.position+=b);try{if(a.path&&S.onWriteToFile)S.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function Ic(){L||(L=function(a,b){this.node=b;this.lc=function(a){this.bb=a};this.lc(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[2].forEach(function(a){Gb[a]=new L(a);Gb[a].stack="<generic error, no stack>"}))}var Jc;function fa(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Kc(a,b,c){a=q("/dev",a);var d=fa(!!b,!!c);Lc||(Lc=64);var e=Lc++<<8|0;Ab(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var g=0,k=0;k<e;k++){try{var m=b()}catch(Ma){throw new L(5);}if(void 0===m&&0===g)throw new L(11);if(null===m||void 0===m)break;g++;c[d+k]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){for(var g=0;g<e;g++)try{c(b[d+g])}catch(ha){throw new L(5);}e&&(a.node.timestamp=Date.now());return g}});
Bc(a,d,e)}var Lc,V={},Sb,zc,Gc,Mc={};
function Nc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&tb(b)!==tb(Nb(e.node)))return-20;throw e;}E[c>>2]=d.dev;E[c+4>>2]=0;E[c+8>>2]=d.ino;E[c+12>>2]=d.mode;E[c+16>>2]=d.nlink;E[c+20>>2]=d.uid;E[c+24>>2]=d.gid;E[c+28>>2]=d.rdev;E[c+32>>2]=0;f=[d.size>>>0,(h=d.size,1<=+Pa(h)?0<h?(Qa(+Ra(h/4294967296),4294967295)|0)>>>0:~~+Sa((h-+(~~h>>>0))/4294967296)>>>0:0)];E[c+40>>2]=f[0];E[c+44>>2]=f[1];E[c+48>>2]=4096;E[c+52>>2]=d.blocks;E[c+56>>2]=d.atime.getTime()/1E3|0;E[c+60>>2]=0;E[c+64>>2]=d.mtime.getTime()/
1E3|0;E[c+68>>2]=0;E[c+72>>2]=d.ctime.getTime()/1E3|0;E[c+76>>2]=0;f=[d.ino>>>0,(h=d.ino,1<=+Pa(h)?0<h?(Qa(+Ra(h/4294967296),4294967295)|0)>>>0:~~+Sa((h-+(~~h>>>0))/4294967296)>>>0:0)];E[c+80>>2]=f[0];E[c+84>>2]=f[1];return 0}var W=0;function X(){W+=4;return E[W-4>>2]}function Y(){return H(X())}function Z(){var a=Q[X()];if(!a)throw new L(9);return a}function Da(){return p.length}
function Oc(a){a=Ya(a);var b=buffer.byteLength;try{return-1!==Ka.grow((a-b)/65536)?(buffer=Ka.buffer,!0):!1}catch(c){return!1}}function Ea(a){if(2147418112<a)return!1;for(var b=Math.max(Da(),16777216);b<a;)536870912>=b?b=Ya(2*b):b=Math.min(Ya((3*b+2147483648)/4),2147418112);if(!Oc(b))return!1;Za();return!0}function Pc(a){if(0===a)return 0;a=H(a);if(!K.hasOwnProperty(a))return 0;Pc.pb&&ca(Pc.pb);a=K[a];var b=na(a)+1,c=Va(b);c&&u(a,p,c,b);Pc.pb=c;return Pc.pb}u("GMT",G,60800,4);
function Qc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Rc){Rc=!0;E[Sc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);E[Tc()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),e=a(c);d=ba(aa(d));e=ba(aa(e));c.getTimezoneOffset()<b.getTimezoneOffset()?(E[Uc()>>2]=d,E[Uc()+4>>2]=e):(E[Uc()>>2]=e,E[Uc()+4>>2]=d)}}var Rc;
function Vc(a){a/=1E3;if((wa||x)&&self.performance&&self.performance.now)for(var b=self.performance.now();self.performance.now()-b<a;);else for(b=Date.now();Date.now()-b<a;);return 0}l._usleep=Vc;Ic();R=Array(4096);Ac(M,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");Ab(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Bc("/dev/null",259);zb(1280,Cb);zb(1536,Db);Bc("/dev/tty",1280);Bc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(A)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){C("random_device")});Kc("random",b);Kc("urandom",b);U("/dev/shm");
U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");Ac({hb:function(){var a=Fb("/proc/self","fd",16895,73);a.$a={lookup:function(a,c){var b=Q[+c];if(!b)throw new L(9);a={parent:null,hb:{Qb:"fake"},$a:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(A){var fs=require("fs"),Hb=require("path");P.mc()}function aa(a,b){var c=Array(na(a)+1);a=u(a,c,0,c.length);b&&(c.length=a);return c}
var Yc=l.asm({},{n:C,l:function(a){return F[a]()},i:function(a,b){return F[a](b)},h:function(a,b,c){return F[a](b,c)},g:function(a,b,c,d){return F[a](b,c,d)},f:function(a,b,c,d,e){return F[a](b,c,d,e)},e:function(a,b,c,d,e,g){return F[a](b,c,d,e,g)},d:function(a,b,c,d,e,g,k){return F[a](b,c,d,e,g,k)},z:function(a,b,c,d,e,g,k){return F[a](b,c,d,e,g,k)},y:function(a,b,c,d,e){return F[a](b,c,d,e)},x:function(a,b,c){return F[a](b,c)},w:function(a,b,c,d){return F[a](b,c,d)},v:function(a,b,c,d,e){return F[a](b,
c,d,e)},c:function(a,b){F[a](b)},b:function(a,b,c){F[a](b,c)},k:function(a,b,c,d){F[a](b,c,d)},j:function(a,b,c,d,e){F[a](b,c,d,e)},u:function(a,b,c,d,e,g){F[a](b,c,d,e,g)},t:function(a,b,c,d){F[a](b,c,d)},m:function(a,b,c,d){C("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},fa:qb,s:rb,ea:function(a,b){W=b;try{var c=Y();sa(c);return 0}catch(d){return"undefined"!==typeof V&&d instanceof L||C(d),-d.bb}},da:function(a,b){W=b;try{return Z(),0}catch(c){return"undefined"!==
typeof V&&c instanceof L||C(c),-c.bb}},ca:function(a,b){W=b;try{var c=Z(),d=X(),e=X(),g=X(),k=X();if(!(-1==d&&0>e||0==d&&0<=e))return-75;Hc(c,e,k);f=[c.position>>>0,(h=c.position,1<=+Pa(h)?0<h?(Qa(+Ra(h/4294967296),4294967295)|0)>>>0:~~+Sa((h-+(~~h>>>0))/4294967296)>>>0:0)];E[g>>2]=f[0];E[g+4>>2]=f[1];c.Db&&0===e&&0===k&&(c.Db=null);return 0}catch(m){return"undefined"!==typeof V&&m instanceof L||C(m),-m.bb}},ba:function(a,b){W=b;try{var c=Y(),d=X();ja(c,d);return 0}catch(e){return"undefined"!==typeof V&&
e instanceof L||C(e),-e.bb}},aa:function(a,b){W=b;try{var c=X(),d=X();if(0===d)return-22;if(d<na("/")+1)return-34;u("/",G,c,d);return c}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.bb}},$:function(a,b){W=b;try{var c=X(),d=X(),e=X(),g=X(),k=X(),m=X();m<<=12;a=!1;if(-1===k){var y=Wc(16384,d);if(!y)return-12;Xc(y,0,d);a=!0}else{var z=Q[k];if(!z)return-9;b=G;if(1===(z.flags&2097155))throw new L(13);if(!z.cb.xb)throw new L(19);var ha=z.cb.xb(z,b,c,d,m,e,g);y=ha.jc;a=ha.Ab}Mc[y]={hc:y,
fc:d,Ab:a,fd:k,flags:g};return y}catch(da){return"undefined"!==typeof V&&da instanceof L||C(da),-da.bb}},_:function(a,b){W=b;try{var c=X();X();var d=X();X();var e=Q[c];if(!e)throw new L(9);if(0===(e.flags&2097155))throw new L(22);Fc(e.node,d);return 0}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.bb}},r:function(a,b){W=b;try{var c=Y(),d=X();return Nc(qa,c,d)}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.bb}},Z:function(a,b){W=b;try{var c=Y(),d=X();return Nc(Dc,c,
d)}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.bb}},Y:function(a,b){W=b;try{var c=Z(),d=X();return Nc(qa,c.path,d)}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.bb}},X:function(a,b){W=b;return 42},W:function(a,b){W=b;return 0},V:function(a,b){W=b;try{var c=X();X();X();var d=Q[c];if(!d)throw new L(9);Ec(d.node);return 0}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.bb}},U:function(a,b){W=b;try{var c=Y();X();X();Ec(c);return 0}catch(d){return"undefined"!==
typeof V&&d instanceof L||C(d),-d.bb}},o:function(a,b){W=b;try{var c=Z();switch(X()){case 0:var d=X();return 0>d?-22:r(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=X(),c.flags|=d,0;case 12:return d=X(),Ha[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return rb(22),-1;default:return-22}}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.bb}},T:function(a,b){W=b;try{var c=Z(),d=X(),e=X();return ra(c,p,d,e)}catch(g){return"undefined"!==
typeof V&&g instanceof L||C(g),-g.bb}},S:function(a,b){W=b;try{var c=Y();var d=X();if(d&-8)var e=-22;else{var g=T(c,{ob:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&Rb(g,a)?-13:0}return e}catch(k){return"undefined"!==typeof V&&k instanceof L||C(k),-k.bb}},R:function(a,b){W=b;try{var c=Y(),d=X();a=c;a=tb(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));U(a,d);return 0}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.bb}},Q:function(a,b){W=b;try{var c=Z(),d=X(),e=X();
return ka(c,p,d,e)}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.bb}},P:function(a,b){W=b;try{var c=Y(),d=T(c,{parent:!0}).node,e=vb(c),g=O(d,e),k=mc(d,e,!0);if(k)throw new L(k);if(!d.$a.rmdir)throw new L(1);if(g.qb)throw new L(16);try{S.willDeletePath&&S.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.$a.rmdir(d,e);Qb(g);try{if(S.onDeletePath)S.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+
c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof V&&m instanceof L||C(m),-m.bb}},O:function(a,b){W=b;try{var c=Y(),d=X(),e=X();return r(c,d,e).fd}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.bb}},q:function(a,b){W=b;try{var c=Z();la(c);return 0}catch(d){return"undefined"!==typeof V&&d instanceof L||C(d),-d.bb}},N:function(a,b){W=b;try{var c=Y(),d=X();var e=X();if(0>=e)var g=-22;else{var k=Mb(c),m=Math.min(e,na(k)),y=p[d+m];u(k,G,d,e+1);p[d+m]=y;
g=m}return g}catch(z){return"undefined"!==typeof V&&z instanceof L||C(z),-z.bb}},M:function(a,b){W=b;try{var c=X(),d=X(),e=Mc[c];if(!e)return 0;if(d===e.fc){var g=Q[e.fd],k=e.flags,m=new Uint8Array(G.subarray(c,c+d));g&&g.cb.yb&&g.cb.yb(g,m,0,d,k);Mc[c]=null;e.Ab&&ca(e.hc)}return 0}catch(y){return"undefined"!==typeof V&&y instanceof L||C(y),-y.bb}},L:function(a,b){W=b;try{var c=X(),d=X(),e=Q[c];if(!e)throw new L(9);ja(e.node,d);return 0}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),
-g.bb}},K:Da,J:function(a,b,c){G.set(G.subarray(b,b+c),a)},I:Ea,p:Pc,H:function(a){var b=Date.now();E[a>>2]=b/1E3|0;E[a+4>>2]=b%1E3*1E3|0;return 0},G:function(a){return Math.log(a)/Math.LN10},F:function(a){Qc();a=new Date(1E3*E[a>>2]);E[15188]=a.getSeconds();E[15189]=a.getMinutes();E[15190]=a.getHours();E[15191]=a.getDate();E[15192]=a.getMonth();E[15193]=a.getFullYear()-1900;E[15194]=a.getDay();var b=new Date(a.getFullYear(),0,1);E[15195]=(a.getTime()-b.getTime())/864E5|0;E[15197]=-(60*a.getTimezoneOffset());
var c=(new Date(2E3,6,1)).getTimezoneOffset();b=b.getTimezoneOffset();a=(c!=b&&a.getTimezoneOffset()==Math.min(b,c))|0;E[15196]=a;a=E[Uc()+(a?4:0)>>2];E[15198]=a;return 60752},E:function(a,b){var c=E[a>>2];a=E[a+4>>2];0!==b&&(E[b>>2]=0,E[b+4>>2]=0);return Vc(1E6*c+a/1E3)},D:function(a){switch(a){case 30:return 16384;case 85:return 131068;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}rb(22);return-1},
C:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b},B:function(a,b){if(b){var c=1E3*E[b+8>>2];c+=E[b+12>>2]/1E3}else c=Date.now();a=H(a);try{b=c;var d=T(a,{ob:!0}).node;d.$a.gb(d,{timestamp:Math.max(b,c)});return 0}catch(e){a=e;if(!(a instanceof L)){a+=" : ";a:{d=Error();if(!d.stack){try{throw Error(0);}catch(g){d=g}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}l.extraStackTrace&&(d+="\n"+l.extraStackTrace());d=Xa(d);throw a+d;}rb(a.bb);return-1}},A:function(){C("OOM")},
a:Ca},buffer);l.asm=Yc;l._RegisterExtensionFunctions=function(){return l.asm.ga.apply(null,arguments)};var pb=l.___emscripten_environ_constructor=function(){return l.asm.ha.apply(null,arguments)};l.___errno_location=function(){return l.asm.ia.apply(null,arguments)};
var Tc=l.__get_daylight=function(){return l.asm.ja.apply(null,arguments)},Sc=l.__get_timezone=function(){return l.asm.ka.apply(null,arguments)},Uc=l.__get_tzname=function(){return l.asm.la.apply(null,arguments)},ca=l._free=function(){return l.asm.ma.apply(null,arguments)},Va=l._malloc=function(){return l.asm.na.apply(null,arguments)},Wc=l._memalign=function(){return l.asm.oa.apply(null,arguments)},Xc=l._memset=function(){return l.asm.pa.apply(null,arguments)};
l._sqlite3_bind_blob=function(){return l.asm.qa.apply(null,arguments)};l._sqlite3_bind_double=function(){return l.asm.ra.apply(null,arguments)};l._sqlite3_bind_int=function(){return l.asm.sa.apply(null,arguments)};l._sqlite3_bind_parameter_index=function(){return l.asm.ta.apply(null,arguments)};l._sqlite3_bind_text=function(){return l.asm.ua.apply(null,arguments)};l._sqlite3_changes=function(){return l.asm.va.apply(null,arguments)};l._sqlite3_clear_bindings=function(){return l.asm.wa.apply(null,arguments)};
l._sqlite3_close_v2=function(){return l.asm.xa.apply(null,arguments)};l._sqlite3_column_blob=function(){return l.asm.ya.apply(null,arguments)};l._sqlite3_column_bytes=function(){return l.asm.za.apply(null,arguments)};l._sqlite3_column_double=function(){return l.asm.Aa.apply(null,arguments)};l._sqlite3_column_name=function(){return l.asm.Ba.apply(null,arguments)};l._sqlite3_column_text=function(){return l.asm.Ca.apply(null,arguments)};l._sqlite3_column_type=function(){return l.asm.Da.apply(null,arguments)};
l._sqlite3_create_function_v2=function(){return l.asm.Ea.apply(null,arguments)};l._sqlite3_data_count=function(){return l.asm.Fa.apply(null,arguments)};l._sqlite3_errmsg=function(){return l.asm.Ga.apply(null,arguments)};l._sqlite3_exec=function(){return l.asm.Ha.apply(null,arguments)};l._sqlite3_finalize=function(){return l.asm.Ia.apply(null,arguments)};l._sqlite3_free=function(){return l.asm.Ja.apply(null,arguments)};l._sqlite3_open=function(){return l.asm.Ka.apply(null,arguments)};
l._sqlite3_prepare_v2=function(){return l.asm.La.apply(null,arguments)};l._sqlite3_reset=function(){return l.asm.Ma.apply(null,arguments)};l._sqlite3_result_double=function(){return l.asm.Na.apply(null,arguments)};l._sqlite3_result_null=function(){return l.asm.Oa.apply(null,arguments)};l._sqlite3_result_text=function(){return l.asm.Pa.apply(null,arguments)};l._sqlite3_step=function(){return l.asm.Qa.apply(null,arguments)};l._sqlite3_value_blob=function(){return l.asm.Ra.apply(null,arguments)};
l._sqlite3_value_bytes=function(){return l.asm.Sa.apply(null,arguments)};l._sqlite3_value_double=function(){return l.asm.Ta.apply(null,arguments)};l._sqlite3_value_int=function(){return l.asm.Ua.apply(null,arguments)};l._sqlite3_value_text=function(){return l.asm.Va.apply(null,arguments)};l._sqlite3_value_type=function(){return l.asm.Wa.apply(null,arguments)};
var n=l.stackAlloc=function(){return l.asm.Ya.apply(null,arguments)},pa=l.stackRestore=function(){return l.asm.Za.apply(null,arguments)},ma=l.stackSave=function(){return l.asm._a.apply(null,arguments)};l.dynCall_vi=function(){return l.asm.Xa.apply(null,arguments)};l.asm=Yc;l.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(a){return"number"===a});return"string"!==b&&e&&!d?Na(a):function(){return Oa(a,b,c,arguments)}};l.stackSave=ma;l.stackRestore=pa;l.stackAlloc=n;
function Zc(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Zc.prototype=Error();Zc.prototype.constructor=Zc;ib=function $c(){l.calledRun||ad();l.calledRun||(ib=$c)};
function ad(){function a(){if(!l.calledRun&&(l.calledRun=!0,!La)){fb||(fb=!0,l.noFSInit||Jc||(Jc=!0,Ic(),l.stdin=l.stdin,l.stdout=l.stdout,l.stderr=l.stderr,l.stdin?Kc("stdin",l.stdin):Cc("/dev/tty","/dev/stdin"),l.stdout?Kc("stdout",null,l.stdout):Cc("/dev/tty","/dev/stdout"),l.stderr?Kc("stderr",null,l.stderr):Cc("/dev/tty1","/dev/stderr"),r("/dev/stdin","r"),r("/dev/stdout","w"),r("/dev/stderr","w")),ab(cb));Lb=!1;ab(db);if(l.onRuntimeInitialized)l.onRuntimeInitialized();if(l.postRun)for("function"==
typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var a=l.postRun.shift();eb.unshift(a)}ab(eb)}}if(!(0<I)){if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)gb();ab(bb);0<I||l.calledRun||(l.setStatus?(l.setStatus("Running..."),setTimeout(function(){setTimeout(function(){l.setStatus("")},1);a()},1)):a())}}l.run=ad;
function C(a){if(l.onAbort)l.onAbort(a);void 0!==a?(Aa(a),D(a),a=JSON.stringify(a)):a="";La=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}l.abort=C;if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.pop()();l.noExitRuntime=!0;ad();



        // The shell-pre.js and emcc-generated code goes above
        return Module;
		
		
    //}); // The end of the promise being returned

  //return initSqlJsPromise;
})(); // The end of our SQL function
/*
// This bit below is copied almost exactly from what you get when you use the MODULARIZE=1 flag with emcc
// However, we don't want to use the emcc modularization. See shell-pre.js
if (typeof exports === 'object' && typeof module === 'object'){
    module.exports = SQL1;
    // This will allow the module to be used in ES6 or CommonJS
    module.exports.default = SQL1;
}
else if (typeof define === 'function' && define['amd']) {
    define([], function() { return SQL1; });
}
else if (typeof exports === 'object'){
    exports["Module"] = SQL1;
}
    
*/
if (typeof module !== 'undefined') module.exports = SQL;
if (typeof define === 'function') define(SQL);
	